name: Other
description: Discuss something related to this project
labels: other
body:
  - type: checkboxes
    attributes:
      label: Check Existing Issues
      description: Check existing open and closed issues to prevent duplicates. Use the search field at the top of the issue tracker. Please only submit a new issue if it has not been covered by an existing issue.
      options:
        - label: I have searched existing issues, and this issue is not a duplicate
          required: true
  - type: textarea
    attributes:
      label: Discussion
      description: Something you would like to discuss. Note that there are separate templates for feature requests and bug reports.
    validations:
      required: true
